Fix navbar fonts.
code4romania/teacher-workout-client pull request #78
Opened 2021-08-06 11:13 UTC by sylar

### What does it fix?
Randomly looking on the project, saw that the navbar's fonts were a bit off. While fixing it thought that would be great not to hardcode the font everywhere since there is already available in the theme config.

Before:
<img width="661" alt="Screenshot 2021-08-06 at 12 10 59 pm" src="https://user-images.githubusercontent.com/2974519/128502010-ab6f0d83-60d4-4e93-866a-00038efc3d31.png">

After:

<img width="604" alt="Screenshot 2021-08-06 at 12 11 39 pm" src="https://user-images.githubusercontent.com/2974519/128502072-e20631ce-e3f1-450c-b80c-24d7b3fd63f3.png">

Just went on the website.

2021-08-10 09:38 UTC, tvararu approved these changes

2021-08-13 13:27 UTC, RaduBuciuceanu approved these changes
Sexy! :heart_eyes:

2021-08-13 13:28 UTC, RaduBuciuceanu requested changes
But let's wait for the linting to finish.

2021-08-13 13:30 UTC, RaduBuciuceanu requested changes
@sylar Can I ask you to fix the linting issues by running `yarn lint:fix`, add the changes to git and push them, please?

2021-08-13 13:30 UTC, sylar commented
sure!

2021-08-13 18:22 UTC, RaduBuciuceanu approved these changes

2021-08-13 18:23 UTC, merged